<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <script>
      function copyValue(){
        var dropboxvalue = document.getElementById('itemdropbox').value;
        document.getElementById('itemtext').value = dropboxvalue;
      }
    </script>
    <div class="main">
      <h4><u>Einkaufsliste v0.7.0</u></h4>

      <!-- Liste -->
      <form action="check.php" method="post" accept-charset="utf-8">
<?php
  // Create a new database, if the file doesn't exist and open it for reading/writing.
  $db = new SQLite3('main_db.sqlite',SQLITE3_OPEN_CREATE | SQLITE3_OPEN_READWRITE);
  if(!$db)
  {
    echo "Error while openening database:";
    echo $db->lastErrorMsg();
    echo "<br/>\n";
    exit;
  } 

  // Create item table if it does not exist:
  //   Elements: id       = autogenerated id element.
  //             item     = text of the item
  //             quantity = optional quantity
  //             check    = done indicator
  $db->exec('CREATE TABLE IF NOT EXISTS "liste" (
             "id"       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
             "item"     TEXT,
             "quantity" TEXT,
             "check"    INTEGER
           )');

  // Create added-items table if it does not exist.
  //   Elements: id       = autogenerated id element.
  //             item     = text of the item
  //             check    = done indicator
  $db->exec('CREATE TABLE IF NOT EXISTS "items" (
             "id"    INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
             "item"  TEXT,
             "check" INTEGER
           )');

  // Fetch items and write them to the form.
  $stmt = $db->prepare('SELECT * FROM "liste"');
  $result = $stmt->execute();
  while ($res = $result->fetchArray(SQLITE3_ASSOC))
  {
    $quant = $res["quantity"];
    $item = $res["item"];
    $checked = $res["check"];

    if ($checked == "1")
    {
      $divclass = "itemon div-item";
      $spanclass = "itemon span-item";
      $buttonclass = "itembuttonon itembutton";
      $checkmark = "";
    }
    else
    {
      $divclass = "itemoff div-item";
      $spanclass = "itemoff span-item";
      $buttonclass = "itembuttonoff itembutton";
      $checkmark = "&checkmark;";
    }

    echo "        <div class=\"".$divclass."\">\n";
    echo "          <span class=\"itemcheck\">".$checkmark."</span>\n";
    echo "          <span class=\"".$spanclass."\">".$quant."</span>\n";
//    echo "          <label class=\"".$spanclass."\">".$quant."</label>\n";
    echo "          <input class=\"".$buttonclass."\" type=\"submit\" name=\"check\" value=\"". $item."\" />\n";
    echo "        </div>\n";
  }
?>
      </form>

      <!-- delete button -->
      <div class="delete">
        <form action="delete.php" method="post">
          <div class="itemsubmit">
            <input class="deletebutton button" type="submit" value="L&ouml;sche Erledigte"/>
          </div>
        </form>
      </div> <!-- delete -->

      <!-- edits for item addition -->
      <div class="add">
        <form action="add.php" method="post" accept-charset="utf-8">
          <!-- A free-text input element with a 'list' of alread added items -->
          <input class="quantfield inputfield" type="text" name="quantity" placeholder="Menge" /> 
          </br> </br>
          <input class="addfield inputfield" type="text" name="name" id="itemtext" list="items" placeholder="Artikel" />
          <input class="addbutton button" type="submit" value="Hinzu" />
          </br> </br>
          <!-- This is not needed anymore as item lists are now supported for iPhone
          <select class="addcombo" id="itemdropbox" onchange="copyValue()">
            <option></option>
          -->
<?php
  // Fetch added-items and write them to the selector.
  // This way, the user gets a list for completion (or other means of pre-selection)
//  $stmt = $db->prepare('SELECT * FROM "items" ORDER BY "item" COLLATE NOCASE ASC');
//  $result = $stmt->execute();
//  while ($res = $result->fetchArray(SQLITE3_ASSOC))
//  {
//    $item = $res["item"];
//
//    echo "            <option>".$item."</option>\n";
//  }
?>
          <!-- This is not needed anymore as item lists are now supported for iPhone
          </select>
          -->
          <datalist id="items">
<?php
  // Fetch added-items and write them to the selector.
  $stmt = $db->prepare('SELECT * FROM "items" ORDER BY "item" COLLATE NOCASE ASC');
  $result = $stmt->execute();
  while ($res = $result->fetchArray(SQLITE3_ASSOC))
  {
    $item = $res["item"];

    echo "            <option>".$item."</option>\n";
  }
?>
          </datalist>
        </form>
      </div> <!-- add -->

      <!-- Button for editing added-items list -->
      <div class="edit">
        <form action="items_index.php" method="post">
          <div class="itemsubmit">
            <input class="editbutton button" type="submit" value="Artikelliste bearbeiten"/>
          </div>
        </form>
      </div> <!-- edit -->

      <!-- vertical space -->
      <div style="height:100px;">
      </div>
    </div> <!-- main -->
  </body>
</html>
